# Server
server:
  port: 80
    
# Database
spring:
  datasource:
    url: jdbc:postgresql://localhost/codenation_logger
    username: postgres
    password: postgres

# Security 
security:
  enabled: true
  enable-https: true

